public enum Categoria{	//Enum usato per le categoria di articoli N.B!!! AGGIORNARE IL DB IN MODO CHE ACCETTI ENUM
	BIRRA, GIN, TONICA, SPRITZ, PROSECCO, VERMOUTH, RUM, WHISKEY, AMARI, ALTRO, VINO, NONSOLOCARTA, FOOD, SINISI
}